### ISSUE TITLE
Not in GZIP format

### ISSUE THREAD

**Issue by moeshin** [RTAkland/QWeatherSDK#1]
```text
Caused by: java.util.zip.ZipException: Not in GZIP format
    at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
    at cn.rtast.qwsdk.utils.HTTPUtilKt.unGZip(HTTPUtil.kt:29)
    at cn.rtast.qwsdk.utils.HTTPUtilKt.get(HTTPUtil.kt:49)
    at cn.rtast.qwsdk.sub.Weather.now(Weather.kt:122)
```

**Comment by RTAkland** [comment]
I've actually been sick recently, so I probably don't have much energy to fix these issues.  sry
